spring:
  session:
    store-type: none
  main:
    banner-mode: console
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html

server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
debug: true
test-sprig-cloud-config-url:
  211111111111111111
