spring:
  session:
    store-type: none
  main:
    banner-mode: console
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
debug: true

