# 连接池
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 10
      min-idle: 5
      max-wait: 15000
      min-evictable-idle-time-millis: 180000
      time-between-eviction-runs-millis: 60000
      remove-abandoned: true
      remove-abandoned-timeout: 600
      log-abandoned: true
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true

  #spring boot redis
  redis:
    password:
    database: 2
    timeout: 100000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    sentinel:
      nodes: redis.uat.chunbo.com:26381
      master: mymaster


##数据源
master:
  mysql:
    url: jdbc:mysql://127.0.0.1:3306/guaiguodpsdb?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
cluster:
  mysql:
    url: jdbc:mysql://127.0.0.1:3306/guaiguodpsdb?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root





