/**
 * Autogenerated by Thrift Compiler (0.9.3)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package top.guaiguo.springdps.self.thrift.generate;


public enum PersonType implements org.apache.thrift.TEnum {
    man(1),
    woman(2);

    private final int value;

    private PersonType(int value) {
        this.value = value;
    }

    /**
     * Get the integer value of this enum value, as defined in the Thrift IDL.
     */
    public int getValue() {
        return value;
    }

    /**
     * Find a the enum type by its integer value, as defined in the Thrift IDL.
     * @return null if the value is not found.
     */
    public static PersonType findByValue(int value) {
        switch (value) {
            case 1:
                return man;
            case 2:
                return woman;
            default:
                return null;
        }
    }
}
