spring:
  application:
    name: guaiguo-dps-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangzygit/cloud-repository
          search-paths: spring-cloud-config
          #私有地址需要配置用户名。密码
server:
  port: 8888

#采用默认配置 EurekaClientConfigBean.DEFAULT_URL
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
